root: true

env:
  es2020: true
  node: true

extends:
  - eslint:recommended
  - prettier

overrides:
  - files: ['*.ts']
    parser: '@typescript-eslint/parser'
    plugins: ['@typescript-eslint']
    extends:
      - eslint:recommended
      - plugin:@typescript-eslint/recommended
      - prettier
