#!/usr/bin/env node

const { InputError } = require('./lib/cli-helpers/input-error')
const { depend } = require('./lib/depend/depend')

depend(process.argv.slice(2), process.stderr).catch(error => {
  if (error instanceof InputError) {
    console.error(error.message)
    process.exit(1)
  } else {
    console.error(error)
    process.exit(2)
  }
})
