#!/usr/bin/env node

const { InputError } = require('./lib/cli/input-error')
const { version } = require('./lib/cli/version')

version(process.argv.slice(2), process.stderr).catch(error => {
  if (error instanceof InputError) {
    console.error(error.message)
    process.exit(1)
  } else {
    console.error(error)
    process.exit(2)
  }
})
